namespace Stunstick.Core.Mdl;

public static class MdlConstants
{
	// "IDST" (little-endian)
	public const uint Idst = 0x54534449;

	// studiohdr_t flags
	public const int StudioHdrFlagsAutogeneratedHitbox = 1 << 0;
	public const int StudioHdrFlagsStaticProp = 1 << 4;

	// Optional studiohdr_t flags used by decompile output.
	public const int StudioHdrFlagsHasShadowLod = 1 << 6;
	public const int StudioHdrFlagsUseShadowlodMaterials = 1 << 8;

	// Bone flags (studio.h)
	public const int BoneUsedByHitbox = 0x00000100;
	public const int BoneUsedByAttachment = 0x00000200;

	public const int BoneUsedByVertexLod0 = 0x00000400;
	public const int BoneUsedByVertexLod1 = 0x00000800;
	public const int BoneUsedByVertexLod2 = 0x00001000;
	public const int BoneUsedByVertexLod3 = 0x00002000;
	public const int BoneUsedByVertexLod4 = 0x00004000;
	public const int BoneUsedByVertexLod5 = 0x00008000;
	public const int BoneUsedByVertexLod6 = 0x00010000;
	public const int BoneUsedByVertexLod7 = 0x00020000;
}
