namespace Stunstick.Core.Mdl;

public sealed record MdlHeader(
	uint Id,
	int Version,
	int Checksum,
	string Name,
	int Length,
	int Flags,
	int BoneCount,
	int BoneOffset,
	int LocalAnimationCount,
	int LocalAnimationOffset,
	int LocalSequenceCount,
	int LocalSequenceOffset,
	int TextureCount,
	int TextureOffset,
	int TexturePathCount,
	int TexturePathOffset,
	int SkinReferenceCount,
	int SkinFamilyCount,
	int SkinFamilyOffset,
	int BodyPartCount,
	int BodyPartOffset,
	int LocalAttachmentCount,
	int LocalAttachmentOffset,
	int FlexDescCount,
	int FlexDescOffset,
	int FlexControllerCount,
	int FlexControllerOffset,
	int FlexRuleCount,
	int FlexRuleOffset,
	int AnimBlockNameOffset,
	int AnimBlockCount,
	int AnimBlockOffset
);
